name       : haskell-lifted-base
version    : 0.2.3.12
release    : 3
source     :
    - https://hackage.haskell.org/package/lifted-base-0.2.3.12/lifted-base-0.2.3.12.tar.gz : c134a95f56750aae806e38957bb03c59627cda16034af9e00a02b699474317c5
license    : BSD-3-Clause
component  : programming.haskell
summary    : lifted-base exports IO operations from the base library lifted to any instance of MonadBase or MonadBaseControl.
description: |
    lifted-base exports IO operations from the base library lifted to any instance of MonadBase or MonadBaseControl.
builddeps  :
    - haskell-cabal-install
    - haskell-monad-control-devel
rundeps    :
    - devel :
        - haskell-monad-control-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
