name       : haskell-lifted-base
version    : 0.2.3.10
release    : 1
source     :
    - http://hackage.haskell.org/package/lifted-base-0.2.3.10/lifted-base-0.2.3.10.tar.gz : e677e560b176c40da2478d2f27dbeadc79630b2295ea3828603e0de4784d24fc
license    : BSD-3-Clause
component  : programming.haskell
summary    : lifted-base exports IO operations from the base library lifted to any instance of MonadBase or MonadBaseControl. 
description: |
    lifted-base exports IO operations from the base library lifted to any instance of MonadBase or MonadBaseControl. 
builddeps  :
    - haskell-cabal-install
    - haskell-monad-control
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
